version: '3.3'

networks:
  main:
    driver: bridge
    ipam:
      config:
        #- subnet: 10.5.0.0/24
        #  gateway: 10.5.0.1

services:
  naming-server:
    image: 'naming_server:latest'
    networks:
      main:
        #ipv4_address: 10.5.0.254

  storage-server-1:
    image: 'storage_server:latest'
    networks:
      - main
    environment:
      NAMING_SERVER_ADDRESS: 'naming-server:5678'

  storage-server-2:
    image: 'storage_server:latest'
    networks:
      - main
    environment:
      NAMING_SERVER_ADDRESS: 'naming-server:5678'



