// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: file_operations.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrorCode int32

const (
	ErrorCode_OK          ErrorCode = 0
	ErrorCode_INITERROR   ErrorCode = 1
	ErrorCode_CREATEERROR ErrorCode = 2
	ErrorCode_READERROR   ErrorCode = 3
	ErrorCode_WRITEERROR  ErrorCode = 4
	ErrorCode_RMERROR     ErrorCode = 5
	ErrorCode_INFERROR    ErrorCode = 6
	ErrorCode_CPERROR     ErrorCode = 7
	ErrorCode_MVERROR     ErrorCode = 8
	ErrorCode_MKDIRERROR  ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "INITERROR",
		2: "CREATEERROR",
		3: "READERROR",
		4: "WRITEERROR",
		5: "RMERROR",
		6: "INFERROR",
		7: "CPERROR",
		8: "MVERROR",
		9: "MKDIRERROR",
	}
	ErrorCode_value = map[string]int32{
		"OK":          0,
		"INITERROR":   1,
		"CREATEERROR": 2,
		"READERROR":   3,
		"WRITEERROR":  4,
		"RMERROR":     5,
		"INFERROR":    6,
		"CPERROR":     7,
		"MVERROR":     8,
		"MKDIRERROR":  9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_file_operations_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_file_operations_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{0}
}

type InitializeArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeArgs) Reset() {
	*x = InitializeArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeArgs) ProtoMessage() {}

func (x *InitializeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeArgs.ProtoReflect.Descriptor instead.
func (*InitializeArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{0}
}

type InitializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode     ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	AvailableSize int64     `protobuf:"varint,2,opt,name=availableSize,proto3" json:"availableSize,omitempty"`
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

func (x *InitializeResult) GetAvailableSize() int64 {
	if x != nil {
		return x.AvailableSize
	}
	return 0
}

type CreateFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CreateFileArgs) Reset() {
	*x = CreateFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileArgs) ProtoMessage() {}

func (x *CreateFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileArgs.ProtoReflect.Descriptor instead.
func (*CreateFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *CreateFileResult) Reset() {
	*x = CreateFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResult) ProtoMessage() {}

func (x *CreateFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResult.ProtoReflect.Descriptor instead.
func (*CreateFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

type ReadFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadFileArgs) Reset() {
	*x = ReadFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileArgs) ProtoMessage() {}

func (x *ReadFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileArgs.ProtoReflect.Descriptor instead.
func (*ReadFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileArgs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	Buffer    []byte    `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *ReadFileResult) Reset() {
	*x = ReadFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResult) ProtoMessage() {}

func (x *ReadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResult.ProtoReflect.Descriptor instead.
func (*ReadFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

func (x *ReadFileResult) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Buffer []byte `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *WriteFileArgs) Reset() {
	*x = WriteFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileArgs) ProtoMessage() {}

func (x *WriteFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileArgs.ProtoReflect.Descriptor instead.
func (*WriteFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFileArgs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WriteFileArgs) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *WriteFileResult) Reset() {
	*x = WriteFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResult) ProtoMessage() {}

func (x *WriteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResult.ProtoReflect.Descriptor instead.
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

type RemoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RemoveArgs) Reset() {
	*x = RemoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveArgs) ProtoMessage() {}

func (x *RemoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveArgs.ProtoReflect.Descriptor instead.
func (*RemoveArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *RemoveResult) Reset() {
	*x = RemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResult) ProtoMessage() {}

func (x *RemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResult.ProtoReflect.Descriptor instead.
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

type GetFileInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetFileInfoArgs) Reset() {
	*x = GetFileInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoArgs) ProtoMessage() {}

func (x *GetFileInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoArgs.ProtoReflect.Descriptor instead.
func (*GetFileInfoArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileInfoArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	Buffer    []byte    `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *GetFileInfoResult) Reset() {
	*x = GetFileInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResult) ProtoMessage() {}

func (x *GetFileInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResult.ProtoReflect.Descriptor instead.
func (*GetFileInfoResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileInfoResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

func (x *GetFileInfoResult) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CopyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *CopyArgs) Reset() {
	*x = CopyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyArgs) ProtoMessage() {}

func (x *CopyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyArgs.ProtoReflect.Descriptor instead.
func (*CopyArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{12}
}

func (x *CopyArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type CopyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *CopyResult) Reset() {
	*x = CopyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResult) ProtoMessage() {}

func (x *CopyResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResult.ProtoReflect.Descriptor instead.
func (*CopyResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{13}
}

func (x *CopyResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

type MoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *MoveArgs) Reset() {
	*x = MoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArgs) ProtoMessage() {}

func (x *MoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArgs.ProtoReflect.Descriptor instead.
func (*MoveArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{14}
}

func (x *MoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MoveArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{15}
}

func (x *MoveResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

type ReadDirectoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadDirectoryArgs) Reset() {
	*x = ReadDirectoryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirectoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirectoryArgs) ProtoMessage() {}

func (x *ReadDirectoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirectoryArgs.ProtoReflect.Descriptor instead.
func (*ReadDirectoryArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{16}
}

func (x *ReadDirectoryArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirectoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
	Buffer    []byte    `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *ReadDirectoryResult) Reset() {
	*x = ReadDirectoryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirectoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirectoryResult) ProtoMessage() {}

func (x *ReadDirectoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirectoryResult.ProtoReflect.Descriptor instead.
func (*ReadDirectoryResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{17}
}

func (x *ReadDirectoryResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

func (x *ReadDirectoryResult) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type MakeDirectoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *MakeDirectoryArgs) Reset() {
	*x = MakeDirectoryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryArgs) ProtoMessage() {}

func (x *MakeDirectoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryArgs.ProtoReflect.Descriptor instead.
func (*MakeDirectoryArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{18}
}

func (x *MakeDirectoryArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MakeDirectoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ErrorCode" json:"errorCode,omitempty"`
}

func (x *MakeDirectoryResult) Reset() {
	*x = MakeDirectoryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryResult) ProtoMessage() {}

func (x *MakeDirectoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryResult.ProtoReflect.Descriptor instead.
func (*MakeDirectoryResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{19}
}

func (x *MakeDirectoryResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_OK
}

var File_file_operations_proto protoreflect.FileDescriptor

var file_file_operations_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x10, 0x0a, 0x0e, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x67, 0x73, 0x22, 0x65, 0x0a,
	0x10, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x50, 0x0a, 0x0c, 0x52,
	0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22,
	0x3e, 0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x20, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x22, 0x3b, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x25,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x58, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22,
	0x38, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x39, 0x0a, 0x0a, 0x43, 0x6f, 0x70,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x39,
	0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x5a, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x27,
	0x0a, 0x11, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x42, 0x0a, 0x13, 0x4d, 0x61, 0x6b, 0x65, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x97, 0x01, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x41, 0x44, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03,
	0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x52, 0x49, 0x54, 0x45, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x4d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05, 0x12, 0x0c, 0x0a,
	0x08, 0x49, 0x4e, 0x46, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x50, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x56, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x08, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x4b, 0x44, 0x49, 0x52, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x09, 0x32, 0xb7, 0x04, 0x0a, 0x15, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2c,
	0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x43, 0x6f, 0x70,
	0x79, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x12, 0x26, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x52, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d,
	0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x41, 0x72, 0x67, 0x73, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_operations_proto_rawDescOnce sync.Once
	file_file_operations_proto_rawDescData = file_file_operations_proto_rawDesc
)

func file_file_operations_proto_rawDescGZIP() []byte {
	file_file_operations_proto_rawDescOnce.Do(func() {
		file_file_operations_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_operations_proto_rawDescData)
	})
	return file_file_operations_proto_rawDescData
}

var file_file_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_file_operations_proto_goTypes = []interface{}{
	(ErrorCode)(0),              // 0: pb.ErrorCode
	(*InitializeArgs)(nil),      // 1: pb.InitializeArgs
	(*InitializeResult)(nil),    // 2: pb.InitializeResult
	(*CreateFileArgs)(nil),      // 3: pb.CreateFileArgs
	(*CreateFileResult)(nil),    // 4: pb.CreateFileResult
	(*ReadFileArgs)(nil),        // 5: pb.ReadFileArgs
	(*ReadFileResult)(nil),      // 6: pb.ReadFileResult
	(*WriteFileArgs)(nil),       // 7: pb.WriteFileArgs
	(*WriteFileResult)(nil),     // 8: pb.WriteFileResult
	(*RemoveArgs)(nil),          // 9: pb.RemoveArgs
	(*RemoveResult)(nil),        // 10: pb.RemoveResult
	(*GetFileInfoArgs)(nil),     // 11: pb.GetFileInfoArgs
	(*GetFileInfoResult)(nil),   // 12: pb.GetFileInfoResult
	(*CopyArgs)(nil),            // 13: pb.CopyArgs
	(*CopyResult)(nil),          // 14: pb.CopyResult
	(*MoveArgs)(nil),            // 15: pb.MoveArgs
	(*MoveResult)(nil),          // 16: pb.MoveResult
	(*ReadDirectoryArgs)(nil),   // 17: pb.ReadDirectoryArgs
	(*ReadDirectoryResult)(nil), // 18: pb.ReadDirectoryResult
	(*MakeDirectoryArgs)(nil),   // 19: pb.MakeDirectoryArgs
	(*MakeDirectoryResult)(nil), // 20: pb.MakeDirectoryResult
}
var file_file_operations_proto_depIdxs = []int32{
	0,  // 0: pb.InitializeResult.errorCode:type_name -> pb.ErrorCode
	0,  // 1: pb.CreateFileResult.errorCode:type_name -> pb.ErrorCode
	0,  // 2: pb.ReadFileResult.errorCode:type_name -> pb.ErrorCode
	0,  // 3: pb.WriteFileResult.errorCode:type_name -> pb.ErrorCode
	0,  // 4: pb.RemoveResult.errorCode:type_name -> pb.ErrorCode
	0,  // 5: pb.GetFileInfoResult.errorCode:type_name -> pb.ErrorCode
	0,  // 6: pb.CopyResult.errorCode:type_name -> pb.ErrorCode
	0,  // 7: pb.MoveResult.errorCode:type_name -> pb.ErrorCode
	0,  // 8: pb.ReadDirectoryResult.errorCode:type_name -> pb.ErrorCode
	0,  // 9: pb.MakeDirectoryResult.errorCode:type_name -> pb.ErrorCode
	1,  // 10: pb.FileOperationsManager.Initialize:input_type -> pb.InitializeArgs
	3,  // 11: pb.FileOperationsManager.CreateFile:input_type -> pb.CreateFileArgs
	5,  // 12: pb.FileOperationsManager.ReadFile:input_type -> pb.ReadFileArgs
	7,  // 13: pb.FileOperationsManager.WriteFile:input_type -> pb.WriteFileArgs
	9,  // 14: pb.FileOperationsManager.Remove:input_type -> pb.RemoveArgs
	11, // 15: pb.FileOperationsManager.GetFileInfo:input_type -> pb.GetFileInfoArgs
	13, // 16: pb.FileOperationsManager.Copy:input_type -> pb.CopyArgs
	15, // 17: pb.FileOperationsManager.Move:input_type -> pb.MoveArgs
	17, // 18: pb.FileOperationsManager.ReadDirectory:input_type -> pb.ReadDirectoryArgs
	19, // 19: pb.FileOperationsManager.MakeDirectory:input_type -> pb.MakeDirectoryArgs
	2,  // 20: pb.FileOperationsManager.Initialize:output_type -> pb.InitializeResult
	4,  // 21: pb.FileOperationsManager.CreateFile:output_type -> pb.CreateFileResult
	6,  // 22: pb.FileOperationsManager.ReadFile:output_type -> pb.ReadFileResult
	8,  // 23: pb.FileOperationsManager.WriteFile:output_type -> pb.WriteFileResult
	10, // 24: pb.FileOperationsManager.Remove:output_type -> pb.RemoveResult
	12, // 25: pb.FileOperationsManager.GetFileInfo:output_type -> pb.GetFileInfoResult
	14, // 26: pb.FileOperationsManager.Copy:output_type -> pb.CopyResult
	16, // 27: pb.FileOperationsManager.Move:output_type -> pb.MoveResult
	18, // 28: pb.FileOperationsManager.ReadDirectory:output_type -> pb.ReadDirectoryResult
	20, // 29: pb.FileOperationsManager.MakeDirectory:output_type -> pb.MakeDirectoryResult
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_file_operations_proto_init() }
func file_file_operations_proto_init() {
	if File_file_operations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_operations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirectoryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirectoryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_operations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_operations_proto_goTypes,
		DependencyIndexes: file_file_operations_proto_depIdxs,
		EnumInfos:         file_file_operations_proto_enumTypes,
		MessageInfos:      file_file_operations_proto_msgTypes,
	}.Build()
	File_file_operations_proto = out.File
	file_file_operations_proto_rawDesc = nil
	file_file_operations_proto_goTypes = nil
	file_file_operations_proto_depIdxs = nil
}
