// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: file_operations.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NodeMode int32

const (
	NodeMode_REGULAR_FILE NodeMode = 0
	NodeMode_DIRECTORY    NodeMode = 1
)

// Enum value maps for NodeMode.
var (
	NodeMode_name = map[int32]string{
		0: "REGULAR_FILE",
		1: "DIRECTORY",
	}
	NodeMode_value = map[string]int32{
		"REGULAR_FILE": 0,
		"DIRECTORY":    1,
	}
)

func (x NodeMode) Enum() *NodeMode {
	p := new(NodeMode)
	*p = x
	return p
}

func (x NodeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_file_operations_proto_enumTypes[0].Descriptor()
}

func (NodeMode) Type() protoreflect.EnumType {
	return &file_file_operations_proto_enumTypes[0]
}

func (x NodeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeMode.Descriptor instead.
func (NodeMode) EnumDescriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{0}
}

type ErrorStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorStatus) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InitializeArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeArgs) Reset() {
	*x = InitializeArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeArgs) ProtoMessage() {}

func (x *InitializeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeArgs.ProtoReflect.Descriptor instead.
func (*InitializeArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{1}
}

type InitializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus   *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	AvailableSize int64        `protobuf:"varint,2,opt,name=availableSize,proto3" json:"availableSize,omitempty"`
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *InitializeResult) GetAvailableSize() int64 {
	if x != nil {
		return x.AvailableSize
	}
	return 0
}

type CreateFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CreateFileArgs) Reset() {
	*x = CreateFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileArgs) ProtoMessage() {}

func (x *CreateFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileArgs.ProtoReflect.Descriptor instead.
func (*CreateFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *CreateFileResult) Reset() {
	*x = CreateFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResult) ProtoMessage() {}

func (x *CreateFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResult.ProtoReflect.Descriptor instead.
func (*CreateFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type ReadFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadFileArgs) Reset() {
	*x = ReadFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileArgs) ProtoMessage() {}

func (x *ReadFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileArgs.ProtoReflect.Descriptor instead.
func (*ReadFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileArgs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	Buffer      []byte       `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *ReadFileResult) Reset() {
	*x = ReadFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResult) ProtoMessage() {}

func (x *ReadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResult.ProtoReflect.Descriptor instead.
func (*ReadFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *ReadFileResult) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteFileArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Buffer []byte `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *WriteFileArgs) Reset() {
	*x = WriteFileArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileArgs) ProtoMessage() {}

func (x *WriteFileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileArgs.ProtoReflect.Descriptor instead.
func (*WriteFileArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileArgs) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFileArgs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WriteFileArgs) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *WriteFileResult) Reset() {
	*x = WriteFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResult) ProtoMessage() {}

func (x *WriteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResult.ProtoReflect.Descriptor instead.
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{8}
}

func (x *WriteFileResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type RemoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RemoveArgs) Reset() {
	*x = RemoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveArgs) ProtoMessage() {}

func (x *RemoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveArgs.ProtoReflect.Descriptor instead.
func (*RemoveArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *RemoveResult) Reset() {
	*x = RemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResult) ProtoMessage() {}

func (x *RemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResult.ProtoReflect.Descriptor instead.
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type GetFileInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetFileInfoArgs) Reset() {
	*x = GetFileInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoArgs) ProtoMessage() {}

func (x *GetFileInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoArgs.ProtoReflect.Descriptor instead.
func (*GetFileInfoArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileInfoArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	FileSize    uint64       `protobuf:"varint,2,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
}

func (x *GetFileInfoResult) Reset() {
	*x = GetFileInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResult) ProtoMessage() {}

func (x *GetFileInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResult.ProtoReflect.Descriptor instead.
func (*GetFileInfoResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileInfoResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *GetFileInfoResult) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type CopyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *CopyArgs) Reset() {
	*x = CopyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyArgs) ProtoMessage() {}

func (x *CopyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyArgs.ProtoReflect.Descriptor instead.
func (*CopyArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{13}
}

func (x *CopyArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type CopyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *CopyResult) Reset() {
	*x = CopyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResult) ProtoMessage() {}

func (x *CopyResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResult.ProtoReflect.Descriptor instead.
func (*CopyResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{14}
}

func (x *CopyResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type MoveArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=newPath,proto3" json:"newPath,omitempty"`
}

func (x *MoveArgs) Reset() {
	*x = MoveArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArgs) ProtoMessage() {}

func (x *MoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArgs.ProtoReflect.Descriptor instead.
func (*MoveArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{15}
}

func (x *MoveArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MoveArgs) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{16}
}

func (x *MoveResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

type ReadDirectoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadDirectoryArgs) Reset() {
	*x = ReadDirectoryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirectoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirectoryArgs) ProtoMessage() {}

func (x *ReadDirectoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirectoryArgs.ProtoReflect.Descriptor instead.
func (*ReadDirectoryArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{17}
}

func (x *ReadDirectoryArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirectoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
	Contents    []*Node      `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *ReadDirectoryResult) Reset() {
	*x = ReadDirectoryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDirectoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirectoryResult) ProtoMessage() {}

func (x *ReadDirectoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirectoryResult.ProtoReflect.Descriptor instead.
func (*ReadDirectoryResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{18}
}

func (x *ReadDirectoryResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

func (x *ReadDirectoryResult) GetContents() []*Node {
	if x != nil {
		return x.Contents
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode NodeMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.NodeMode" json:"mode,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{19}
}

func (x *Node) GetMode() NodeMode {
	if x != nil {
		return x.Mode
	}
	return NodeMode_REGULAR_FILE
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MakeDirectoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *MakeDirectoryArgs) Reset() {
	*x = MakeDirectoryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryArgs) ProtoMessage() {}

func (x *MakeDirectoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryArgs.ProtoReflect.Descriptor instead.
func (*MakeDirectoryArgs) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{20}
}

func (x *MakeDirectoryArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MakeDirectoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorStatus *ErrorStatus `protobuf:"bytes,1,opt,name=errorStatus,proto3" json:"errorStatus,omitempty"`
}

func (x *MakeDirectoryResult) Reset() {
	*x = MakeDirectoryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_operations_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryResult) ProtoMessage() {}

func (x *MakeDirectoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_operations_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryResult.ProtoReflect.Descriptor instead.
func (*MakeDirectoryResult) Descriptor() ([]byte, []int) {
	return file_file_operations_proto_rawDescGZIP(), []int{21}
}

func (x *MakeDirectoryResult) GetErrorStatus() *ErrorStatus {
	if x != nil {
		return x.ErrorStatus
	}
	return nil
}

var File_file_operations_proto protoreflect.FileDescriptor

var file_file_operations_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x43, 0x0a, 0x0b, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72,
	0x67, 0x73, 0x22, 0x6b, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x24, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x45, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50, 0x0a, 0x0c,
	0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5b,
	0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x0d, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a, 0x0a,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x41,
	0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31,
	0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x38, 0x0a, 0x08,
	0x43, 0x6f, 0x70, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3f, 0x0a, 0x0a, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x3f, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x6e, 0x0a, 0x13, 0x52,
	0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x04, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x4d, 0x61, 0x6b,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x48, 0x0a, 0x13, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x2b, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x47, 0x55,
	0x4c, 0x41, 0x52, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x01, 0x32, 0xb7, 0x04, 0x0a, 0x15, 0x46, 0x69,
	0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x41, 0x72, 0x67, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x26, 0x0a,
	0x04, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x41,
	0x72, 0x67, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0d, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_file_operations_proto_rawDescOnce sync.Once
	file_file_operations_proto_rawDescData = file_file_operations_proto_rawDesc
)

func file_file_operations_proto_rawDescGZIP() []byte {
	file_file_operations_proto_rawDescOnce.Do(func() {
		file_file_operations_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_operations_proto_rawDescData)
	})
	return file_file_operations_proto_rawDescData
}

var file_file_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_file_operations_proto_goTypes = []interface{}{
	(NodeMode)(0),               // 0: pb.NodeMode
	(*ErrorStatus)(nil),         // 1: pb.ErrorStatus
	(*InitializeArgs)(nil),      // 2: pb.InitializeArgs
	(*InitializeResult)(nil),    // 3: pb.InitializeResult
	(*CreateFileArgs)(nil),      // 4: pb.CreateFileArgs
	(*CreateFileResult)(nil),    // 5: pb.CreateFileResult
	(*ReadFileArgs)(nil),        // 6: pb.ReadFileArgs
	(*ReadFileResult)(nil),      // 7: pb.ReadFileResult
	(*WriteFileArgs)(nil),       // 8: pb.WriteFileArgs
	(*WriteFileResult)(nil),     // 9: pb.WriteFileResult
	(*RemoveArgs)(nil),          // 10: pb.RemoveArgs
	(*RemoveResult)(nil),        // 11: pb.RemoveResult
	(*GetFileInfoArgs)(nil),     // 12: pb.GetFileInfoArgs
	(*GetFileInfoResult)(nil),   // 13: pb.GetFileInfoResult
	(*CopyArgs)(nil),            // 14: pb.CopyArgs
	(*CopyResult)(nil),          // 15: pb.CopyResult
	(*MoveArgs)(nil),            // 16: pb.MoveArgs
	(*MoveResult)(nil),          // 17: pb.MoveResult
	(*ReadDirectoryArgs)(nil),   // 18: pb.ReadDirectoryArgs
	(*ReadDirectoryResult)(nil), // 19: pb.ReadDirectoryResult
	(*Node)(nil),                // 20: pb.Node
	(*MakeDirectoryArgs)(nil),   // 21: pb.MakeDirectoryArgs
	(*MakeDirectoryResult)(nil), // 22: pb.MakeDirectoryResult
}
var file_file_operations_proto_depIdxs = []int32{
	1,  // 0: pb.InitializeResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 1: pb.CreateFileResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 2: pb.ReadFileResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 3: pb.WriteFileResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 4: pb.RemoveResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 5: pb.GetFileInfoResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 6: pb.CopyResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 7: pb.MoveResult.errorStatus:type_name -> pb.ErrorStatus
	1,  // 8: pb.ReadDirectoryResult.errorStatus:type_name -> pb.ErrorStatus
	20, // 9: pb.ReadDirectoryResult.contents:type_name -> pb.Node
	0,  // 10: pb.Node.mode:type_name -> pb.NodeMode
	1,  // 11: pb.MakeDirectoryResult.errorStatus:type_name -> pb.ErrorStatus
	2,  // 12: pb.FileOperationsManager.Initialize:input_type -> pb.InitializeArgs
	4,  // 13: pb.FileOperationsManager.CreateFile:input_type -> pb.CreateFileArgs
	6,  // 14: pb.FileOperationsManager.ReadFile:input_type -> pb.ReadFileArgs
	8,  // 15: pb.FileOperationsManager.WriteFile:input_type -> pb.WriteFileArgs
	10, // 16: pb.FileOperationsManager.Remove:input_type -> pb.RemoveArgs
	12, // 17: pb.FileOperationsManager.GetFileInfo:input_type -> pb.GetFileInfoArgs
	14, // 18: pb.FileOperationsManager.Copy:input_type -> pb.CopyArgs
	16, // 19: pb.FileOperationsManager.Move:input_type -> pb.MoveArgs
	18, // 20: pb.FileOperationsManager.ReadDirectory:input_type -> pb.ReadDirectoryArgs
	21, // 21: pb.FileOperationsManager.MakeDirectory:input_type -> pb.MakeDirectoryArgs
	3,  // 22: pb.FileOperationsManager.Initialize:output_type -> pb.InitializeResult
	5,  // 23: pb.FileOperationsManager.CreateFile:output_type -> pb.CreateFileResult
	7,  // 24: pb.FileOperationsManager.ReadFile:output_type -> pb.ReadFileResult
	9,  // 25: pb.FileOperationsManager.WriteFile:output_type -> pb.WriteFileResult
	11, // 26: pb.FileOperationsManager.Remove:output_type -> pb.RemoveResult
	13, // 27: pb.FileOperationsManager.GetFileInfo:output_type -> pb.GetFileInfoResult
	15, // 28: pb.FileOperationsManager.Copy:output_type -> pb.CopyResult
	17, // 29: pb.FileOperationsManager.Move:output_type -> pb.MoveResult
	19, // 30: pb.FileOperationsManager.ReadDirectory:output_type -> pb.ReadDirectoryResult
	22, // 31: pb.FileOperationsManager.MakeDirectory:output_type -> pb.MakeDirectoryResult
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_file_operations_proto_init() }
func file_file_operations_proto_init() {
	if File_file_operations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_operations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirectoryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDirectoryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_operations_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_operations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_operations_proto_goTypes,
		DependencyIndexes: file_file_operations_proto_depIdxs,
		EnumInfos:         file_file_operations_proto_enumTypes,
		MessageInfos:      file_file_operations_proto_msgTypes,
	}.Build()
	File_file_operations_proto = out.File
	file_file_operations_proto_rawDesc = nil
	file_file_operations_proto_goTypes = nil
	file_file_operations_proto_depIdxs = nil
}
