// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NamingClient is the client API for Naming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamingClient interface {
	Register(ctx context.Context, in *RegRequest, opts ...grpc.CallOption) (*RegResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
}

type namingClient struct {
	cc grpc.ClientConnInterface
}

func NewNamingClient(cc grpc.ClientConnInterface) NamingClient {
	return &namingClient{cc}
}

func (c *namingClient) Register(ctx context.Context, in *RegRequest, opts ...grpc.CallOption) (*RegResponse, error) {
	out := new(RegResponse)
	err := c.cc.Invoke(ctx, "/pb.Naming/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namingClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, "/pb.Naming/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamingServer is the server API for Naming service.
// All implementations must embed UnimplementedNamingServer
// for forward compatibility
type NamingServer interface {
	Register(context.Context, *RegRequest) (*RegResponse, error)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	mustEmbedUnimplementedNamingServer()
}

// UnimplementedNamingServer must be embedded to have forward compatible implementations.
type UnimplementedNamingServer struct {
}

func (UnimplementedNamingServer) Register(context.Context, *RegRequest) (*RegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNamingServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedNamingServer) mustEmbedUnimplementedNamingServer() {}

// UnsafeNamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamingServer will
// result in compilation errors.
type UnsafeNamingServer interface {
	mustEmbedUnimplementedNamingServer()
}

func RegisterNamingServer(s *grpc.Server, srv NamingServer) {
	s.RegisterService(&_Naming_serviceDesc, srv)
}

func _Naming_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Naming/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServer).Register(ctx, req.(*RegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Naming_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Naming/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Naming_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Naming",
	HandlerType: (*NamingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Naming_Register_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Naming_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "naming_services.proto",
}
