// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StorageDiscoveryClient is the client API for StorageDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageDiscoveryClient interface {
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
}

type storageDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageDiscoveryClient(cc grpc.ClientConnInterface) StorageDiscoveryClient {
	return &storageDiscoveryClient{cc}
}

func (c *storageDiscoveryClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, "/pb.StorageDiscovery/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageDiscoveryServer is the server API for StorageDiscovery service.
// All implementations must embed UnimplementedStorageDiscoveryServer
// for forward compatibility
type StorageDiscoveryServer interface {
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	mustEmbedUnimplementedStorageDiscoveryServer()
}

// UnimplementedStorageDiscoveryServer must be embedded to have forward compatible implementations.
type UnimplementedStorageDiscoveryServer struct {
}

func (UnimplementedStorageDiscoveryServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedStorageDiscoveryServer) mustEmbedUnimplementedStorageDiscoveryServer() {}

// UnsafeStorageDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageDiscoveryServer will
// result in compilation errors.
type UnsafeStorageDiscoveryServer interface {
	mustEmbedUnimplementedStorageDiscoveryServer()
}

func RegisterStorageDiscoveryServer(s *grpc.Server, srv StorageDiscoveryServer) {
	s.RegisterService(&_StorageDiscovery_serviceDesc, srv)
}

func _StorageDiscovery_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageDiscoveryServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StorageDiscovery/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageDiscoveryServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StorageDiscovery",
	HandlerType: (*StorageDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _StorageDiscovery_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ss_discovery.proto",
}
